### ISSUE TITLE
Error: Cannot resolve module 'vue'

### ISSUE THREAD

**Issue by yidan621** [cookingjs/cookingjs.github.io#2]
I did 
npm i cooking -g
cooking create my-project vue
cooking watch
cooking build 

After everything was installed, the server started with an error: 
[cooking] - Listening at http://localhost:8080
Child cooking.conf.js:

```
ERROR in ./src/main.js
Module not found: Error: Cannot resolve module 'vue' in /my-project/src
 @ ./src/main.js 3:11-25

ERROR in ./src/app.vue
Module not found: Error: Cannot resolve module 'vue' in /my-project/src
 @ ./src/app.vue 15:17-31
```

What was wrong??

**Comment by QingWei-Li** [comment]
`vue` is installed?

**Comment by yidan621** [comment]
I've installed `vue` globally via `npm install vue -g` but not under `node_modules` directory. 

After installing 'vue' under `node_modules`, it works fine! 

Thanks！
